language: python
python:
    - 3.6

install:
  - pip install -r requirements.txt
script:
  - python src/main.py knn --test-run --pca=43
  - python src/main.py log --test-run
  - python src/main.py mlp --test-run --distort=all
  - python src/main.py qda --test-run --small
  - python src/main.py svc --test-run --similarity=sim_cos
  - python src/main.py lda --small
