(define (batch-resize-digits pattern)
  (let* ((filelist (cadr (file-glob pattern 1))))
    (while (not (null? filelist))
      (let* ((filename (car filelist))
        (image (car (gimp-file-load RUN-NONINTERACTIVE filename filename)))
        (drawable (car (gimp-image-get-active-layer image))))
      (plug-in-autocrop RUN-NONINTERACTIVE image drawable)
      (gimp-file-save RUN-NONINTERACTIVE image drawable filename filename)
      (set! filelist (cdr filelist))))))
